version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - npm run build
      - serverless deploy