version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - node --version
      - npm run build
      - serverless deploy